import os from 'os'
//const os = require('os')
console.log(os.arch())
console.log(os.release())
console.log(os.totalmem())
console.log(os.freemem())
console.log(os.version())
console.log(os.platform())
console.log(os.type())
console.log(os.tmpdir())